# Generated by Django 3.0.8 on 2020-07-26 14:43
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('book_id', models.UUIDField()),
                ('buyer_id', models.UUIDField()),
                ('purchased_at', models.DateTimeField()),
            ],
        ),
    ]
