# Generated by Django 3.0.8 on 2020-07-26 14:45
import random
import uuid

from django.db import migrations
from django.utils import timezone

NUM_BOOKS = 500
NUM_BUYERS = 5_000
NUM_PURCHASES = 1_000

DATE_BETWEEN = (timezone.now() - timezone.timedelta(days=365), timezone.now())


def random_date(start, end):
    return start + timezone.timedelta(
        seconds=random.randint(0, int((end - start).total_seconds())),
    )

def populate_purchase(apps, schema_editor):
    Purchase = apps.get_model("bookstore", "Purchase")

    books = [uuid.uuid4() for book in range(NUM_BOOKS)]
    books = [uuid.uuid4() for book in range(NUM_BOOKS)]
    
    for _ in range(NUM_PURCHASES):
        params = {
            "book_id": random.choice(books),
            "buyer_id": random.choice(books),
            "purchased_at": random_date(*DATE_BETWEEN),
        }
        
        purchase = Purchase(**params)
        purchase.save()


def clear_purchase(apps, schema_editor):
    Purchase = apps.get_model("bookstore", "Purchase")

    Purchase.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_purchase, reverse_code=clear_purchase),
    ]
