# Generated by Django 3.0.8 on 2020-07-26 16:50

from django.db import migrations

def reinsert_objects(apps, schema_editor):
    Purchase = apps.get_model("bookstore", "Purchase")

    purchase_ids = Purchase.objects.all().values_list("id", flat=True)
    for purchase_id in purchase_ids:
        purchase = Purchase.objects.get(pk=purchase_id)
        purchase.delete()

        purchase.save()

class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_populate_purchase'),
    ]

    operations = [
        migrations.RunPython(reinsert_objects, reverse_code=migrations.RunPython.noop),
    ]
